name: Tests
on:
  push:

jobs:
  tests:
    name: Test on Node ${{ matrix.node-version }}
    strategy:
      matrix:
        # do not test on Node 18 as the node:test module supports lcov only from 20.11.0 onwards
        node-version: [ '20', '22', '24' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run tests
        run: npm test
